config/routes.rb
Rails.application.routes.draw do

  #----- Devise routes-----
  # This will generate all the routes for the User model through the devise gem
  devise_for :users
  #----- Devise routes -----

  # Defines the root path route ("/")
  root 'blog_posts#index'

  #----- Blog Posts routes -----
  # :id is a dynamic segment, which will be replaced with the ID of the blog post

  ## - "as: new_blog_post" gives the route a name, which can be used in the view helper as 'new_blog_post_path'
  ## - the 'new' route will always be above the 'show' route, otherwise the 'show' route will be used instead of the 'new' route
  # get '/blog_posts/new', to: 'blog_posts#new', as: :new_blog_post

  # ## - "as: blog_post" gives the route a name, which can be used in the view helper as 'blog_post_path'
  # get '/blog_posts/:id', to: 'blog_posts#show', as: :blog_post

  # ## - we need this route to handle the form submission from the 'new' route
  # post '/blog_posts', to: 'blog_posts#create', as: :blog_posts

  # ## - This route will be used to display the edit form
  # get '/blog_posts/:id/edit', to: 'blog_posts#edit', as: :edit_blog_post

  # ## - This route will be used to handle the form submission from the 'edit' route
  # patch '/blog_posts/:id', to: 'blog_posts#update'

  # ## - This route will be used to delete a blog post
  # delete '/blog_posts/:id', to: 'blog_posts#destroy'
  #----- Blog Posts routes -----

  resources :blog_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  # ----- Scopes -----
  # BlogPost.sorted
  scope :sorted, -> { order(arel_table[:published_at].desc.nulls_last).order(updated_at: :desc) }

  # BlogPost.draft
  scope :draft, -> { where(published_at: nil) }

  # BlogPost.published
  scope :published, -> { where('published_at <= ?', Time.current) }

  # BlogPost.scheduled
  scope :scheduled, -> { where('published_at > ?', Time.current) }
  # ----- Scopes -----

  # ----- Helper methods to use in views -----
  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
  # ----- Helper methods to use in views -----
end

=begin

Status string field:
- draft
- published
- scheduled

'published_at' datetime field
- draft - nil
- published - 1.year.ago - time
- published - 1.year.from_now - time

=end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
  end

  def show
    # @blog_post = BlogPost.find(params[:id])
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # We need to find the blog post we want to edit, and store to the instance variable @blog_post
    #  in order to display the blog post title and body in the form
    # @blog_post = BlogPost.find(params[:id])
  end

  def update
    # @blog_post = BlogPost.find(params[:id])

    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    # @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    redirect_to root_path
  end

  private

  # Strong Parameters - to protect against mass assignment. This is a mandatory step in Rails 4 and above.
  def blog_post_params
    params.require(:blog_post).permit(:title, :body, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : BlogPost.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post) do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message|  %>
       <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :published %>
    <%= form.datetime_select :published_at, include_blank: true %>
  </div>

  <div>
    <%= form.button %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%# we pass the local variable into the partial %>
<%= render partial: 'form', locals: {blog_post: @blog_post} %>

<%#                                                  turbo rails %>
<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/blog_posts/index.html.erb
<h1>My blog posts</h1>

<% @blog_posts.each do |blog_post| %>
  <% if blog_post.draft? %>
    <div class="p-1 rounded bg-gray-100 text-gray-900 mb-4">
      <h2 class="mt-0">
        <%= link_to blog_post.title, blog_post %>
        <span> - 📝</span>
      </h2>
      <p><%= blog_post.body%></p>
    </div>
  <% elsif blog_post.scheduled? %>
    <div class="p-2 rounded bg-blue-100 text-gray-900 mb-4">
      <h2 class="mt-0">
        <%= link_to blog_post.title, blog_post %>
        <span> - 🗓️</span>
      </h2>
      <p><%= blog_post.body%></p>
    </div>
  <% elsif blog_post.published? %>
    <% if user_signed_in? %>
      <div class="p-2 rounded bg-green-100 text-gray-900 mb-4">
        <h2 class="mt-0">
          <%= link_to blog_post.title, blog_post %>
          <span> - ✅</span>
        </h2>
        <p><%= blog_post.body%></p>
      </div>
    <% else %>
      <div class="border-2 border-black">
        <h2 class="mt-0">
          <%= link_to blog_post.title, blog_post %>
        </h2>
        <p><%= blog_post.body%></p>
      </div>
    <% end %>
  <% end %>
<% end%>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%# we pass the local variable into the partial %>
<%= render partial: 'form', locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<%= link_to  "Edit blog post", edit_blog_post_path(@blog_post) if user_signed_in? %>

<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoRailsBlogProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if user_signed_in? %>
        <%= link_to  "New blog post", new_blog_post_path %>
        <%# <%= link_to  "Profile", edit_user_registration_path %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      <%# <% else %>
        <%# <%= link_to "Log in", new_user_session_path %>
        <%# <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </div>

    <%= yield %>

  </body>
</html>